name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make valgrind
      run: make valgrind

